[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/neoyank.vim'
depends = 'denite.nvim'
on_event = 'TextYankPost'

# ---
[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
          \'colorscheme': 'solarized',
      \ }
'''

# プラグイン

[[plugins]]
repo = 'w0rp/ale'

# Colors

[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'

# [[plugins]] # railscasts
# repo = 'KeitaNakamura/railscasts.vim'

# vim-easy-alignの設定

[[plugins]] # vim-easy-align
repo = 'junegunn/vim-easy-align'

# 括弧の保管

[[plugins]] # lexima
repo = 'cohama/lexima.vim'

# editorconfigの設定

[[plugins]] # editorconfig
repo = 'editorconfig/editorconfig-vim'

# Lang

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

# [[plugins]] # css3
# repo = 'hail2u/vim-css3-syntax'
# on_ft = 'css'

[[plugins]] # css
repo = 'JulesWang/css.vim' # only necessary if your Vim version < 7.4
on_ft = ['scss', 'css']

[[plugins]] # Scss
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'

[[plugins]] # vim-coloresque
repo = 'gko/vim-coloresque'
on_ft = 'css'

[[plugins]] # vue
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]] # yajs.vim
repo = 'othree/yajs.vim'
on_ft = 'js'

[[plugins]] # ESlint
repo = 'benjie/neomake-local-eslint.vim'
on_ft = 'js'

[[plugins]] # vim-json
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
'''

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]] # nerdtree
repo = 'scrooloose/nerdtree'

[[plugins]] # vim-stylefmt
repo = 'kewah/vim-stylefmt'

[[plugins]] # neosnippet-snippets
repo = 'Shougo/neosnippet-snippets'
