[[plugins]] # Codic
repo = 'koron/codic-vim'
on_cmd = 'Codic'

# Markdown setting
[[plugins]] # quote内のプログラムをシンタックスハイライトする
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown','mkd']

[[plugins]] # 編集中のMarkdownファイルのプレビューを作成する
repo = 'kannokanno/previm'
on_ft = ['markdown','mkd']

[[plugins]]# プレビューをブラウザで開いてくれる
repo = 'tyru/open-browser.vim'
on_ft = ['markdown','mkd']
# ここまで

[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
on_i = 1
hook_source = '''
    let g:user_emmet_mode = 'i'
    let g:user_emmet_leader_key='<C-E>'
    let g:use_emmet_complete_tag = 1
    let g:user_emmet_settings = {
    \   'variables': {
    \       'lang': "ja"
    \   },
    \   'indentation': '    '
    \}
'''

[[plugins]] # EditorConfig
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'

[[plugins]] # snippet
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]] # denite.nvim
repo = 'Shougo/denite.nvim'
on_event = 'BufRead'
hook_add = '''
  nmap <silent> <C-u><C-t> :<C-u>Denite filetype<CR>
  nmap <silent> <C-u><C-p> :<C-u>Denite file_rec<CR>
  nmap <silent> <C-u><C-j> :<C-u>Denite line<CR>
  nmap <silent> <C-u><C-g> :<C-u>Denite grep -buffer-name=search-buffer-denite<CR>
  nmap <silent> <C-u><C-r> :<C-u>Denite -resume -buffer-name=search-buffer-denite<CR>
  nmap <silent> <C-u><C-]> :<C-u>DeniteCursorWord grep<CR>
  nmap <silent> <C-u><C-u> :<C-u>Denite file_mru<CR>
  nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
  nmap <silent> <C-u>; :<C-u>Denite -resume -immediately -select=+1<CR>
  nmap <silent> <C-u>- :<C-u>Denite -resume -immediately -select=-1<CR>
  nmap <silent> <C-u><C-d> :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/dotfiles']}])<CR>
  nnoremap ml :<C-u>call denite#start([{'name': 'file_rec', 'args': [g:memolist_path]}])<CR>
'''

# denite設定 - ag
hook_post_source = '''
  call denite#custom#var('file_rec', 'command',
  \ ['ag', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
  call denite#custom#var('grep', 'command',
  \ ['ag', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
  call denite#custom#var('grep', 'default_opts', [])
  call denite#custom#var('grep', 'recursive_opts', [])
'''
